spring:
  application:
    name: cacheredis

  cache:
    # 强制使用Redis作为Cache:
    type: Redis

  redis:
    host: localhost
    port: 6379
    # Redis数据库索引（默认为0）
    database: 0
    # Redis连接密码（默认为空）
    # password: xxx
    pool:
      # 连接池最大连接数
      max-active: 8
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 2
      # 连接池最大阻塞等待时间
      max-wait: 2000
      # 连接超时时间
      timeout: 500

server:
  port: 9090
