### application default profile ###

# spring config:
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_IP:172.27.0.101}:3306/petstore?useSSL=false&autoReconnect=true
    username: root
    # get encrypted string by:
    # curl -d 'original-string' http://<config-server>:8888/encrypt
    password: '{cipher}b38de5599e160c5d83ef67f9ba660f1a77c0e8527dba9d2dd99bc59e564e2bb8'
  jpa:
    show-sql: true
    database: mysql
    properties:
      javax:
        persistence:
          schema-generation:
            database:
              action: none
            scripts:
              action: none
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  sleuth:
    enabled: true
    sampler:
      percentage: 0.1
    hystrix:
      strategy:
        enabled: false
    stream:
      enabled: true
  rabbitmq:
    addresses: ${RABBITMQ_IP:172.27.0.103}:5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        mailChannel:
          destination: mail
          contentType: application/json
          group: mail
          consumer:
            maxAttempts: 5

# default http port is set to 8080:
server:
  port: 8080

# timeout for rest invocation:
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000

# eureka config:
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_IP:172.27.0.201}:8761/eureka/
